### ISSUE TITLE
Fails on quadmath

### ISSUE THREAD

**Issue by andk** [sanko/template-liquid#10]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/111904615

Relation between nvtype and success: http://analysis.cpantesters.org/reports_by_field?distv=Template-Liquid-1.0.19;field=conf%3Anvtype;order=2ta

**Comment by sanko** [comment]
Fixed in https://github.com/sanko/template-liquid/commit/355e4cb788e9efc8bc55f7b08709a947d95e278e

Thanks.
