### ISSUE TITLE
comparison conditions failed if there is no whitespace between variable/string and equality operator

### ISSUE THREAD

**Issue by amit777** [sanko/template-liquid#20]
if the template has something like this (notice the lack of space around the second `'hi'`):
```perl
use strict;
use warnings;
use lib qw[./lib ./blib/lib];
use Template::Liquid;

# Various condition types
my $tpl = "{% if 'hi' =='hi' %}One equals one{% else %}FAIL{% endif %}";
my $rendered = Template::Liquid->parse($tpl)->render();

print $rendered;
```

We get an error because parsing the condition doesn't work.

if we modify the regex in `Condition.pm` on Line 27 to the following, I think I got it working.  At least all the test suite passes.

```
# current regex
    my ($lval, $condition, $rval)
        = ((defined $args->{'attrs'} ? $args->{'attrs'} : '')
            =~ m[("[^"]+"|'[^']+'|(?:[\S]+))]go);

# fixed regex
    my ($lval, $condition, $rval)
        = ((defined $args->{'attrs'} ? $args->{'attrs'} : '')
            =~ m[("[^"]+"|'[^']+'|(?:eq|==|ne|!=|lt|<|gt|>|contains|&&|\|\|)|(?:[\w.]+))]go);

```

**Comment by amit777** [comment]
I'll create a pull request shortly.   I made the capture group for the various eqauly operators more specific.  I also changed the `[\S]+` to `[\w]+` so that the equality operator signs don't get caught up in the match group.

**Comment by amit777** [comment]
Thank you for merging the PRs!   I was wondering if it would be easy to publish a new release?

**Comment by sanko** [comment]
I haven't used Template::Liquid in at least a decade and wrote it 13 or 14 years ago. I'm so unfamiliar with it code's internals that I would almost rewrite it all when a new issue pops up.

I'll need to revisit it to accept #17 but I'll push it to PAUSE today without it.
